apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gna-frontend-ingress
  namespace: gna-staging
  annotations:
    kubernetes.io/ingress.class: 'traefik'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: gna-staging-redirect-https@kubernetescrd
spec:
  rules:
    - host: 'gna-frontend.k3s.bangun-kreatif.com'
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: gna-fe
                port:
                  number: 3000
  tls:
    - hosts:
        - 'gna-frontend.k3s.bangun-kreatif.com'
      secretName: gna-frontend-k3s-bangun-kreatif-com-tls
